### ISSUE TITLE
How about binding parameters?

### ISSUE THREAD

**Issue by sasha172017** [mavinoo/laravelBatch#109]
How about binding parameters? It makes sql injection now. It is dangerous.

**Comment by mavinoo** [comment]
Yes, using bound parameters to prevent SQL injection is crucial. By using bound parameters, input data is properly filtered and sanitized, and if necessary, translated. Without using bound parameters, the system is vulnerable and at risk from a security standpoint. It's always better to ensure that input data is properly filtered and sanitized and to use bound parameters. However, in this package, the mysql_escape method is used to prevent at least some malicious inputs.

https://github.com/mavinoo/laravelBatch/blob/d931f44316ee35747933b339b7cc9b96a162f6be/src/Common/Common.php#L13
