### ISSUE TITLE
Update only on integer keys?

### ISSUE THREAD

**Issue by MADAOLEX** [mavinoo/laravelBatch#11]
Hi!

There is one limitation in your function updateMultipleRows, it works only if $index is integer.
But if you use instead of 
```
$query = "UPDATE `$table` SET " . substr($cases, 0, -2) . " WHERE `$index` IN(" . implode(',', $ids) . ");";
```
this:
```
$query = "UPDATE `$table` SET " . substr($cases, 0, -2) . " WHERE `$index` IN(" . '"' . implode('","', $ids) . '"' . ");";
```
you can use strings as $index too.

I use this almost two months now, no crashes or errors.

**Comment by eaharonoff** [comment]
@MADAOLEX can you submit the PR? Would love that functionality added here!

**Comment by MADAOLEX** [comment]
@eaharonoff Done. #12 
I hope I did it right, because I do not have such experience.
