### ISSUE TITLE
Why not implement update by unlimited  multiple colums in where clause?

### ISSUE THREAD

**Issue by videni** [mavinoo/laravelBatch#110]
hi, thanks for this awesome libary, Can I ask the question  why not implement  batch update by by unlimited  multiple colums in where clause. I noticed there is a `updateWithTwoIndex` method, it can do batch update by two columns,  but how about three, four , more?

**Comment by mavinoo** [comment]
hi @videni 
add method multiple condition 
[v2.4](https://github.com/mavinoo/laravelBatch/releases/tag/v2.4)
