### ISSUE TITLE
Is query protected against sql injection attack

### ISSUE THREAD

**Issue by tylik1** [mavinoo/laravelBatch#13]
By quickly looking into code, i saw you're using escape function that you wrote yourself. Do you think it will help to protect against sql injection attack?

**Comment by 1000nettles** [comment]
This is also a concern for me, we shouldn't need to roll our own SQL escaping functionality.

Could we replace it with the answer outlined here? https://stackoverflow.com/a/23208367/823549

**Comment by tylik1** [comment]
@mavinoo  by closing this issue, do you confirm that your helper is safe to use, or you fixed it somehow?

**Comment by mavinoo** [comment]
hi @tylik1 you get last committed, Optimized as much as possible.
