### ISSUE TITLE
Too few arguments to function 

### ISSUE THREAD

**Issue by Evhanz** [mavinoo/laravelBatch#15]
![screenshot_20190221_184032](https://user-images.githubusercontent.com/7060754/53209365-3cd8f300-3608-11e9-8513-94101507d199.png)

Sorry guys, but I have a big problem, in the last update I found this error in all the code that I used with its amazing package, I would love to fix it as fast as possible, help me please.

in my Code :

$columns = [
                'a',
                'b',
                'c',
            ];
            $batch = new Batch
            $batch->insert('polls_schedulers_areas', $columns, $data, 200);

**Comment by mavinoo** [comment]
hi @Evhanz 
use table model instead of table name
https://github.com/mavinoo/laravelBatch/pull/14

**Comment by mavinoo** [comment]
At last commit
You send the model instead of the table name.

```
use Batch;
use App\Models\PollsSchedulersAreas;

$model = new PollsSchedulersAreas;

$columns = [
   'a',
   'b',
   'c'
];

$data = [
   ['a1', 'b1', 'c1'],
   ['a2', 'b2', 'c3'],
];
Batch::insert($model, $columns, $data, 200);
```

**Comment by Evhanz** [comment]
Sorry for not answering, but version 2.0 worked for how the project was already done, but we will see if we move to the latest version, excellent work thanks
