### ISSUE TITLE
Call to undefined method 

### ISSUE THREAD

**Issue by Brenden848** [mavinoo/laravelBatch#18]
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined method Mavinoo\LaravelBatch\LaravelBatchFacade::update()

I am receiving the error above even after registering the package in app.php. I have used this package before but it was version one. I am wondering what the correct course of action would be to resolve the issue.

**Comment by mavinoo** [comment]
tnx @Brenden848 
bug fixed https://github.com/mavinoo/laravelBatch/commit/491c0d5af37ff28f51f034d87b7953f6f3e76a57
