### ISSUE TITLE
Facade doesn't seem to work 

### ISSUE THREAD

**Issue by MikeMnD** [mavinoo/laravelBatch#2]
At least with 5.5 - so i needed to set it like:

`use Mavinoo\LaravelBatch\LaravelBatchFacade as Batch;`

or else when Batch::update is called goes to` ErrorException: Non-static method Mavinoo\LaravelBatch\Batch::update() should not be called statically`

Generally it'sgood practice to put the facade in namespace/folder Facade and the class name to be the same as the facade.

Just check most of the other packages.

**Comment by mavinoo** [comment]
You must first
In the app.php file, add two items in the config folder that are named in the README.md file.

1. Service Provider
2. Aliases

 https://github.com/mavinoo/laravelBatch/blob/master/README.md

And then use the defined facade.

example:
[Example Batch Update 1](https://github.com/mavinoo/laravelBatch/blob/master/README.md#example-update-1)
[Example Batch Update 2](https://github.com/mavinoo/laravelBatch/blob/master/README.md#example-update-2)
[Example Batch Insert](https://github.com/mavinoo/laravelBatch/blob/master/README.md#example-insert)

**Comment by MikeMnD** [comment]
These two lines were added in the app.php in config

**Comment by mavinoo** [comment]
not use facade Batch => use Batch in aliases app.php in config

![examples_1](https://user-images.githubusercontent.com/16878523/35850576-8fec202a-0b3a-11e8-8b7b-4c59dd6e4559.png)

or with use facade batch

![examples_2](https://user-images.githubusercontent.com/16878523/35850577-9016f71e-0b3a-11e8-90ac-4ec5d8f37bc7.png)
