### ISSUE TITLE
How to get updated instance

### ISSUE THREAD

**Issue by dododaphne** [mavinoo/laravelBatch#23]
```php
use App\Models\User;

$userInstance = new User;
$value = [
     [
         'id' => 1,
         'status' => 'active',
         'nickname' => 'Mohammad'
     ] ,
     [
         'id' => 5,
         'status' => 'deactive',
         'nickname' => 'Ghanbari'
     ] ,
];
$index = 'id';
Batch::update($userInstance, $value, $index);
```
After ***Batch::update***, I want to access updated objects., like this:
```php
$updatedUser=Batch::update($userInstance, $value, $index);
$updatedUser->where('country','UK')->get();
```
But  ```$updatedUser``` is a total number of updated array, so what can I do?
Thank you~

**Comment by djunehor** [comment]
SQL update queries usually returns the rows affected, so the implementation is right in returning an array of updated rows.

You can easily do something like `$userInstance->where('country', 'UK')->get();` which will return the up-to-date model instance

**Comment by dododaphne** [comment]
Thanks for replay. What if I don't want to get all up-to-date data. For example, if I have a table which contains 10 thousands users. I just updated 500 users, and I only want to get 'country' from 'UK' among the 500 users, how could I do?

**Comment by djunehor** [comment]
You can achieve that this way:
```
$ids = array_column($value, 'id');
$userInstance->whereIn('id', $ids)->where('country', 'UK')->get(); 
```

**Comment by dododaphne** [comment]
That’s a simple and clean solution, thank you very much!
