### ISSUE TITLE
Does not work for pgsql ( postgresql )

### ISSUE THREAD

**Issue by shaikhabdulqadir** [mavinoo/laravelBatch#28]
the solution works for mysql but not for pgsql, there is query error for pgsql, I have updated code pgsql as well, please update if you think this is ok

update function code in LaravelBatch.php file

`
public function update(Model $table, array $values, string $index = null, bool $raw = false)
    {
        $final = [];
        $ids = [];

        if (!count($values)) {
            return false;
        }

        if (!isset($index) || empty($index)) {
            $index = $table->getKeyName();
        }

        foreach ($values as $key => $val) {
            $ids[] = $val[$index];
            foreach (array_keys($val) as $field) {
                if ($field !== $index) {
                    $finalField = $raw ? Common::mysql_escape($val[$field]) : "'" . Common::mysql_escape($val[$field]) . "'";
                    $value = (is_null($val[$field]) ? 'NULL' : $finalField);
                    $final[$field][] = 'WHEN "' . $index . '" = \'' . $val[$index] . '\' THEN ' . $value . ' ';
                }
            }
        }

        $connection = config('database.default');

        $driver = config("database.connections.{$connection}.driver");

        if ( $driver == 'pgsql' ){

            $cases = '';
            foreach ($final as $k => $v) {
                $cases .= '"' . $k . '" = (CASE ' . implode("\n", $v) . "\n"
                    . 'ELSE "' . $k . '" END), ';
            }

             $query = "UPDATE \"" . $this->getFullTableName($table) . '" SET ' . substr($cases, 0, -2) . " WHERE \"$index\" IN('" . implode("','", $ids) . "');";

        }else{

            $cases = '';
            foreach ($final as $k => $v) {
                $cases .= '`' . $k . '` = (CASE ' . implode("\n", $v) . "\n"
                    . 'ELSE `' . $k . '` END), ';
            }

             $query = "UPDATE `" . $this->getFullTableName($table) . "` SET " . substr($cases, 0, -2) . " WHERE `$index` IN(" . '"' . implode('","', $ids) . '"' . ");";

        }
        

        return $this->db->connection($this->getConnectionName($table))->update($query);
    }`

**Comment by footballman17** [comment]
@shaikhabdulqadir thx man, it helped me a lot! -)

**Comment by mavinoo** [comment]
[Added support for batch support for postgres](https://github.com/mavinoo/laravelBatch/commit/9bec55b20e89680b232cdf79e3f3023977f5dbf8)
