### ISSUE TITLE
NULL gets replaced with ""

### ISSUE THREAD

**Issue by valivvvv** [mavinoo/laravelBatch#3]
I believe the update function replaces `null` values with `""` (an empty string), which leads to sql errors; can't assign` ""` to an `INT` column, for example.

**Comment by mavinoo** [comment]
hi @valivvvv 
Thanks for the report
[fixed bug](https://github.com/mavinoo/laravelBatch/commit/c1fbb26cc4cb776f27f8164bd591416a44a97821)

Please re-install.

**Comment by valivvvv** [comment]
Thanks for a great plugin, all the best!

**Comment by sasokovacic** [comment]
@mavinoo this is still not working in my case

**Comment by sasokovacic** [comment]
it seems there is a problem with phpmyadmin. It shows me empty string instead of null for integer columns. So, everything works as expected.
