### ISSUE TITLE
Syntax error ERROR:  syntax error at or near 

### ISSUE THREAD

**Issue by Taalaybek** [mavinoo/laravelBatch#31]
I get some errors while i try to update records
here is my array 
`$array = [
  [
    'flm' => 'alexis rozaline',
    'card_type' => 'MasterCard',
    'card_number' => '.....',
    'id' => 1
  ]
]`
`\batch()->update(new BankDetail(), $request->get('bank_details'), 'id');`
**how can i resolve this?**

**Comment by Taalaybek** [comment]
i'm using postgres, laravel 5.8

**Comment by mavinoo** [comment]
[Added support for batch support for postgres](https://github.com/mavinoo/laravelBatch/commit/9bec55b20e89680b232cdf79e3f3023977f5dbf8)
