### ISSUE TITLE
Not compatible Composer v2

### ISSUE THREAD

**Issue by lkmadushan** [mavinoo/laravelBatch#32]
Deprecation Notice: Class Mavinoo\LaravelBatch\Batch located in ./vendor/mavinoo/laravel-batch/src/LaravelBatch.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0

**Comment by mavinoo** [comment]
hi
please config app.php

[providers](https://github.com/mavinoo/laravelBatch/tree/v2.0#service-provider), [aliases](https://github.com/mavinoo/laravelBatch/tree/v2.0#aliases)

**Comment by lorvent** [comment]
i just tried that but still it displays same error.

```
Deprecation Notice: Class Mavinoo\LaravelBatch\Batch located in C:/laragon/www/sms/vendor/mavinoo/laravel-batch/src\LaravelBatch.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0
```

**Comment by mavinoo** [comment]
What is the Laravel version?

**Comment by mavinoo** [comment]
please read issues: [Deprecation notices for PSR-4 autoloading with correct paths?](https://github.com/composer/composer/issues/8683)

**Comment by envatic** [comment]
Its something to do with class name not matching file name
`Deprecation Notice: Class Mavinoo\LaravelBatch\Batch located in ./vendor/mavinoo/laravel-batch/src/LaravelBatch.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. `
renaming `src/LaravelBatch.php` to `src/Batch.php` solves the issue

**Comment by stemis** [comment]
@mavinoo Your `LaravelBatch.php` file contains a class named `Batch`, this must be renamed to `LaravelBatch`, same as the filename.

Composer is now checking these things and warning users so they can do something about it before moving to Composer v2.

**Comment by lorvent** [comment]
Can you please release a new version aswell?

**Comment by stemis** [comment]
@lorvent the PR submitted only renames the class, but the references from other files to this class need to be renamed as well.

**Comment by lorvent** [comment]
oops, so it needs another PR.

**Comment by mavinoo** [comment]
Fixed

**Comment by lorvent** [comment]
Glad to know,
is it ready for release now?

**Comment by mavinoo** [comment]
@lorvent [v2.1.5](https://github.com/mavinoo/laravelBatch/tree/v2.1.5)
