### ISSUE TITLE
2.1.5 / Laravel Framework 6.18.13

### ISSUE THREAD

**Issue by vtsakhilov** [mavinoo/laravelBatch#34]
Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Mavinoo\LaravelBatch\Batch' not found

  at /var/www/html/Admin_gow/admin.backuped.site/vendor/mavinoo/laravel-batch/src/LaravelBatchServiceProvider.php:16
    12|      */
    13|     public function register()
    14|     {
    15|         $this->app->bind('LaravelBatch', function ($app){
  > 16|             return new Batch($app->make(DatabaseManager::class));
    17|         });
    18|     }
    19| }
    20|

  Exception trace:

  1   Mavinoo\LaravelBatch\LaravelBatchServiceProvider::Mavinoo\LaravelBatch\{closure}(Object(Illuminate\Foundation\Application), [])
      /var/www/html/Admin_gow/admin.backuped.site/vendor/laravel/framework/src/Illuminate/Container/Container.php:799

  2   Illuminate\Container\Container::build(Object(Closure))
      /var/www/html/Admin_gow/admin.backuped.site/vendor/laravel/framework/src/Illuminate/Container/Container.php:681

  Please use the argument -v to see more details.
Script @php artisan ide-helper:generate handling the post-update-cmd event returned with error code 1

**Comment by vtsakhilov** [comment]
on 2.1.4 all working correct

**Comment by Revolta77** [comment]
Please rewrite LaravelBatchServiceProvider.php on line 16 return new Batch($app->make(DatabaseManager::class)); to return new LaravelBatch($app->make(DatabaseManager::class));

**Comment by vtsakhilov** [comment]
fixed. Thx.
