### ISSUE TITLE
Publish a new release with Batch problem solved

### ISSUE THREAD

**Issue by alrik11es** [mavinoo/laravelBatch#35]
```json
{
    "message": "Class 'Mavinoo\\LaravelBatch\\Batch' not found",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/home/vagrant/code/xxxxxxx-core/vendor/mavinoo/laravel-batch/src/LaravelBatchServiceProvider.php",
    "line": 16
....
}
```
I saw that you have fixed the "Batch" class problem on the ServiceProvider in the master branch. Can you publish a new release with this fix so we can establish a fixed version for our projects?

Thanks.

**Comment by mavinoo** [comment]
install version 2.1.4 .
in version 2.1.5+ , Rename Class `Batch` to `LaravelBatch` .

**Comment by alrik11es** [comment]
Thanks for passing by but I have a problem with the 2.1.4:

![image](https://user-images.githubusercontent.com/249844/81802302-186f7c00-9516-11ea-8a11-61cdf57597cb.png)

![image](https://user-images.githubusercontent.com/249844/81802368-3937d180-9516-11ea-8458-f1e671380638.png)

As you can see in version 2.1.4 the problem will still occur. What can I do?

Thanks again.

**Comment by nepetadosmil** [comment]
@mavinoo Any chance you can create a new release with this fix, please? Composer doesn't grab the master branch and modifying contents in the vendor folder is a no-no.

**Comment by mavinoo** [comment]
@nepetadosmil @alrik11es 
install release 2.1.6

**Comment by mavinoo** [comment]
@alrik11es @nepetadosmil 
install release v2.1.7

**Comment by nepetadosmil** [comment]
Thank you very much! :)

**Comment by mavinoo** [comment]
@alrik11es @nepetadosmil 
install 2.1.8

**Comment by nepetadosmil** [comment]
Great! 😃
