### ISSUE TITLE
Class 'Mavinoo\Batch\ServiceProvider' not found

### ISSUE THREAD

**Issue by shevtsov-max** [mavinoo/laravelBatch#36]
I started today "composer update" and got the error "'Class 'Mavinoo\Batch\ServiceProvider' not found". Rolled back to version 2.1.5

**Comment by WebMedic-X** [comment]
Got the same issue

**Comment by mavinoo** [comment]
tnx for report bug.
fixed 2.1.8

**Comment by Gavrisimo** [comment]
@mavinoo can you enable tests to run against every pull requests so these things don't happen?

There is also an issue with namespace for which I sent PR: https://github.com/mavinoo/laravelBatch/pull/37
