### ISSUE TITLE
 Class 'Mavinoo\LaravelBatch\LaravelBatchServiceProvider' not found  

### ISSUE THREAD

**Issue by salvadorcea** [mavinoo/laravelBatch#38]
Hi im having this error in Laravel:
> php artisan optimize
 In ProviderRepository.php line 208:
                                                                     
 Class 'Mavinoo\LaravelBatch\LaravelBatchServiceProvider' not found  
                                                                    
Script php artisan optimize handling the post-update-cmd event returned with error code 1

**Comment by salvadorcea** [comment]
solved forcing version 2.1.5 in composer:
"mavinoo/laravel-batch": "2.1.5",

**Comment by mstojanovv** [comment]
@salvadorcea **LaravelBatchServiceProvider** is renamed and belong to a new namespace, check the readme to get familiar with the new classes, you will need to change the **Batch** alias too.

Hope this help.

**Comment by Aurabolt** [comment]
@mstojanovv I have the same error as @salvadorcea . I manually changed my app.php to use the new values in the readme but I can't get my composer update or install to finish cleanly. "composer dumpautoload" also fails with the same error. 

This is a major breaking change that was not documented. I expect everyone who was using LaravelBatch now has a broken app after trying to do a regular "composer update".

**Comment by Aurabolt** [comment]
I fixed the issue by manually editing bootstrap/cache/config.php and removing the whole line that had "LaravelBatch". Then, "composer dumpautoload" worked.

**Comment by ezzycreative1** [comment]
hi, i am also experiencing the same problem. 
In Application.php line 635:
Class 'Mavinoo\LaravelBatch\LaravelBatchServiceProvider' not found 
After running rm composer.lock and composer install --prefer-dist --no-scripts --no-dev -o.
Can you help me this problem ?

**Comment by perle-rare** [comment]
I have the  same issue after running composer update
please any help ?? my project is broken and I can't do any progress

**Comment by perle-rare** [comment]
I get-it fix after these changes :
in my config/app.php  

Mavinoo\LaravelBatch\LaravelBatchServiceProvider::class, => **Mavinoo\Batch\BatchServiceProvider::class**,

* 'Batch' => Mavinoo\LaravelBatch\LaravelBatchFacade::class, => 'Batch' =>**Mavinoo\Batch\BatchFacade::class**,

and after that, I run composer update

**Comment by havanan** [comment]
> I get-it fix after these changes :
> in my config/app.php
> 
> * Mavinoo\LaravelBatch\LaravelBatchServiceProvider::class, => **Mavinoo\Batch\BatchServiceProvider::class**,
> * 'Batch' => Mavinoo\LaravelBatch\LaravelBatchFacade::class, => 'Batch' =>**Mavinoo\Batch\BatchFacade::class**,
> 
> and after that, I run `composer update`

thank

**Comment by sfaya** [comment]
Hi,

After migrating a laravel project to a VPS (ubuntu 20.04), I got the same error. 
I tried @havanan solution but running composer update the error persists 
Any ideas please?
( I'm using laravel-batch:dev-master)
