### ISSUE TITLE
ErrorException: Non-static method Mavinoo\LaravelBatch\Batch::update() should not be called statically

### ISSUE THREAD

**Issue by markdza** [mavinoo/laravelBatch#4]
I have Laravel 5.5.28

I did the following:

1. *composer require mavinoo/laravel-batch:dev-master*
2. In config/app.php, providers array, added: *Mavinoo\LaravelBatch\LaravelBatchServiceProvider::class,*
3. In config/app.php, aliases array, added: *'Batch' => Mavinoo\LaravelBatch\LaravelBatchFacade::class,*
4. In my job I have included this on top: *use Mavinoo\LaravelBatch\Batch;*
5. In the same job file I then used it like: *Batch::update('datatable', $data, 'id');*

But I get the following error:

> ErrorException: Non-static method Mavinoo\LaravelBatch\Batch::update() should not be called statically

I even tried taking step 4 out, but I got the same error

What's wrong?

**Comment by mavinoo** [comment]
hi
I'm excited for the late reply.
Please see this issue
https://github.com/mavinoo/laravelBatch/issues/2#issuecomment-363357431

**Comment by markdza** [comment]
I fixed this by putting a \ before Batch::update
