### ISSUE TITLE
Issue in Bulk Update

### ISSUE THREAD

**Issue by atefrihane** [mavinoo/laravelBatch#45]
Hey I'm trying to bulk update a model but I'm facing this issue

**"Class Mavinoo\Batch\Batch contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Mavinoo\Batch\BatchInterface::updateWithTwoIndex)"
trace: []**

This is my code

```
$audioInstance = new Audio;
            $value = $record['audios'];
            $index = 'id';
           
            batch()->update($audioInstance, $value, `$index);`
```

Using Laravel 6 !

**Comment by mavinoo** [comment]
hey @atefrihane 
tnx for issue.

install [v2.2.1](https://github.com/mavinoo/laravelBatch/releases/tag/v2.2.1).

**Comment by corsair** [comment]
This is still occurring on 2.2.1 on Laravel 8. @mavinoo

**Comment by mavinoo** [comment]
hi @corsair 
I do not think it is a problem.
