### ISSUE TITLE
Index wrapping issue

### ISSUE THREAD

**Issue by mstojanovv** [mavinoo/laravelBatch#46]
Hello.

https://github.com/mavinoo/laravelBatch/blob/0b6302ad6b0fb79d7955b813beb54101f11eb7ad/src/Batch.php#L75

In Batch.php line number 75 the index is not properly wrapped for MySQL.

`$final[$field][] = 'WHEN "' . $index . '" = \'' . $val[$index] . '\' THEN ' . $value . ' ';`

Should be:

```$final[$field][] = 'WHEN `' . $index . '` = \'' . $val[$index] . '\' THEN ' . $value . ' ';```

It was working in previous versions but seems like recent commits have broken this feature, can you double-check it?

Regards.

**Comment by mavinoo** [comment]
hi @mstojanovv 
tnx for issues
[v2.2.2](https://github.com/mavinoo/laravelBatch/tree/v2.2.2)
