### ISSUE TITLE
Call to undefined function Mavinoo\Batch\now()  in Batch.php line 242

### ISSUE THREAD

**Issue by salmonerasmus** [mavinoo/laravelBatch#49]
Hi there,

This package used to work fine for version 2.1, but I have recently run into the following error. 

I have tried to install version 2.2 but I still getting the following error that the following function is undefined. `now()`.

When I tried to update `now()->format($table->getDateFormat())` to `date($table->getDateFormat())` on line 67 and 242 of Batch.php it seems to work fine. Is this a solution as the database entries looks good.

**Comment by quanruxiaohong** [comment]
same problem for me.

**Comment by regive** [comment]
I'm on lumen 8, it seems that now() is a carbon helper which doesn't exist for me so I'm getting the same error.

**Comment by HilbertGilbertson** [comment]
Likewise, on Lumen 8 this is a bother, although a quick and easy fix. Seems to have emerged since 13b829d.
