### ISSUE TITLE
while the type of index is string, update error

### ISSUE THREAD

**Issue by freedomfee** [mavinoo/laravelBatch#5]
line 65 in src/LaravelBatch.php
$query = 'UPDATE ' . $table . ' SET '. substr($cases, 0, -2) . ' WHERE ' . $index . ' IN('.implode(',', $ids).')';

while the index type is string 

also, the value string should escaped like this:

 DB::connection()->getPdo()->quote($val[$field]))

**Comment by mavinoo** [comment]
hi
fixed bug in commit
https://github.com/mavinoo/laravelBatch/commit/87f2f1c7aea986a96fec73dd5bd3b2b67af16cc4
