### ISSUE TITLE
How to add where condition for update method?

### ISSUE THREAD

**Issue by hhuseyn** [mavinoo/laravelBatch#51]
How to add where condition for update method? for example
        $product_model = new Product;  //where count > 100
        $index = 'id';
        $value = [
            [
                'id' => 1,
                'count' => 5
            ],
        ];

**Comment by mavinoo** [comment]
$index in $values is key for condition

**Comment by hhuseyn** [comment]
How to??
Batch::update($product_model , $value, $index);
i want add new condition in Product model.
Product where only show_index = 1(products table column) then Batch::update($product_model , $value, $index);
Please help me
