### ISSUE TITLE
Add new where condition???

### ISSUE THREAD

**Issue by hhuseyn** [mavinoo/laravelBatch#52]
Hi. How to??
$product_model = new Product; 
$index = 'id';
$value = [
['id' => 1,'count' => 5],
['id' => 2,'count' => 3],
];

Batch::update($product_model , $value, $index);
i want add new condition in Product model.
Product where only show_index = 1(products table column)  Batch::update($product_model , $value, $index);
Please help me

**Comment by mavinoo** [comment]
batch update only one condition.

```
$product_model = new Product;

$index = 'show_index';

$value = [
 ['show_index' => 1,'count' => 5],
 ['show_index' => 2,'count' => 3],
];

Batch::update($product_model , $value, $index);
```

**Comment by Zzombiee2361** [comment]
I think he meant multiple where condition, that's what I wanted to ask anyway. Like for example I have a `settings` table with `user_id`, `key`, and `value` columns. I'd like to use `user_id` and `key` as the condition to update `value` column

**Comment by WalterWoshid** [comment]
Try Batch::updateWithTwoIndex($model, $data, $index, $index2)

**Comment by Zzombiee2361** [comment]
Whoa, why isn't this documented in the readme

**Comment by WalterWoshid** [comment]
@Zzombiee2361 does it work? If it does, I'll add it to the readme

**Comment by sandeep0108** [comment]
> Try Batch::updateWithTwoIndex($model, $data, $index, $index2)

It's working for me. But it's working for update only, if record does not exist then not creating

**Comment by mavinoo** [comment]
hi @hhuseyn 
add method multiple condition 
[v2.4](https://github.com/mavinoo/laravelBatch/releases/tag/v2.4)
