### ISSUE TITLE
How set NULL?

### ISSUE THREAD

**Issue by bizvid** [mavinoo/laravelBatch#75]
I have:

`
[
  [
    "id" => "40142"
    "invoice_number" => null
  ],
  [
    "id" => "40108"
    "invoice_number" => "555"
  ]
]
`

Case with null - don't work. How can i insert null in batch update process?

**Comment by mavinoo** [comment]
hi @bizvid 
add method multiple condition 
[v2.4](https://github.com/mavinoo/laravelBatch/releases/tag/v2.4)
