### ISSUE TITLE
exception : should not be called statically

### ISSUE THREAD

**Issue by ylnwqm** [mavinoo/laravelBatch#81]
PHP Version : 7.4.9
Laravel Version : 8.0

`app.php`
```
'providers' => [
        Mavinoo\Batch\BatchServiceProvider::class,
 ],

'aliases' => [
        'Batch' => Mavinoo\Batch\BatchFacade::class,
],
```

when i  use `Batch::update($userInstance, $value, $index);`

An exception occurred 
`Non-static method Mavinoo\Batch\Batch::update() should not be called statically`

But use `batch()->update($userInstance, $value, $index);`    no exception in this way

**Comment by mavinoo** [comment]
hi @ylnwqm  
reinstall package or update package to **2.3.4**

### **insert**
![batch-insert](https://user-images.githubusercontent.com/16878523/166189199-7fa853e1-4d52-49f0-ace8-bc2b0a15bd81.png)

### **update**
![batch-update](https://user-images.githubusercontent.com/16878523/166189187-b1c76bfa-4aa4-4a0f-92cb-7ca6e9ce4421.png)

**Comment by joe820912boy** [comment]
nice!! this solve the same problem

**Comment by joe820912boy** [comment]
@mavinoo I want to further understand could I add the 'providers' and 'alias' in my custimized service provider in my packages?

Or just could add it to app.php in config folder?
