### ISSUE TITLE
ParseError: syntax error, unexpected 'return' (T_RETURN) in version 2.3.2, 2.3.3.

### ISSUE THREAD

**Issue by eleazarbr** [mavinoo/laravelBatch#86]
You probably already know, but updating the package version to `2.3.2` or `2.3.3` generates the next error:

```
ParseError: syntax error, unexpected 'return' (T_RETURN)
in /vendor/mavinoo/laravel-batch/src/Batch.php:275
```

I had to set the package to version 2.3.1 to avoid that error.
Btw awesome package. Thanks

**Comment by szhorvath** [comment]
Hi, 
The same problem here. 
![image](https://user-images.githubusercontent.com/38496732/164190166-1cbfa278-1da7-4e96-86f9-7e16dce5b03d.png)

**Comment by kuteikin** [comment]
Please add ) in /vendor/mavinoo/laravel-batch/src/Batch.php:line247
