### ISSUE TITLE
Request for new version

### ISSUE THREAD

**Issue by pataar** [mavinoo/laravelBatch#89]
Hello @mavinoo,

Currently the package is not possible due the syntax error you've recently fixed. Any chance in releasing a new version containing the fix? Thanks in advance!

**Comment by mavinoo** [comment]
reinstall package or update package to **2.3.4**

![batch-insert](https://user-images.githubusercontent.com/16878523/166188406-73ac0cf9-74cf-4d01-a919-c0d7d654c9c9.png)

**Comment by pataar** [comment]
Thanks!
