### ISSUE TITLE
the new releases after 2.3.1 has a bug in file Batch.php  - Insert Function

### ISSUE THREAD

**Issue by thaifanisalla** [mavinoo/laravelBatch#90]
in line    (https://github.com/mavinoo/laravelBatch/blob/126f077dec4ecabb67331694e71bf28b427daa60/src/Batch.php#L274)

in release 2.3.1 and earlier  this line was 

````php  
if (count($columns) !== count($values[0])) {  

````

in the latest release it changes to 
````php
if (count($columns) !== count(current($values))) {
````
and it cause  a bug for us when send array values of rows  
please revert it Or fix it

**Comment by slimak12** [comment]
@mavinoo Could you create new Release with https://github.com/mavinoo/laravelBatch/commit/126f077dec4ecabb67331694e71bf28b427daa60 included ?

**Comment by mavinoo** [comment]
reinstall package or update package to **2.3.4**

![batch-insert](https://user-images.githubusercontent.com/16878523/166188347-61371a9b-24ae-4d0c-8883-dfa39ea93f29.png)
