### ISSUE TITLE
Syntax error, unexpected token "return" :: 275 line

### ISSUE THREAD

**Issue by bizvid** [mavinoo/laravelBatch#91]
Before 2.3.2 update laravel-btach works ok, now i'm getting error:
**syntax error, unexpected token "return"**

about this line:
...../vendor/mavinoo/laravel-batch/src/Batch.php:275
https://plik24.ovh/zrzut_ekranowy/220427_115042_5960.png

**Comment by bizvid** [comment]
I use composer update and error still occurs. I use 2.3.3 version of mavinoo/laravel-batch

**Comment by cha0ran** [comment]
yes,me too. Update to the latest 2.3.3 in Composer

**Comment by mavinoo** [comment]
reinstall package or update package to 2.3.4

![batch-insert](https://user-images.githubusercontent.com/16878523/166188127-5c93a31b-c517-4cd8-aebb-4836031c2e97.png)
